apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 10.36.11.202/demo/myapp:latest
        ports:
        - containerPort: 8080
          name: metrics
        - containerPort: 10001
          name: web
